Models/Summernote.cs
namespace WebAnToanVeSinhThucPhamDemo.Models
{
    public class Summernote
    {
        public Summernote(string iDEditor, bool loadLibrary = true)
        {
            IDEditor = iDEditor;
            LoadLibrary = loadLibrary;
        }

        public string IDEditor { get; set; }
        public bool LoadLibrary { get; set; }
        public int height { get; set; } = 120;
    }
}

Controllers/CoSoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using WebAnToanVeSinhThucPhamDemo.Models;

namespace WebAnToanVeSinhThucPhamDemo.Controllers
{
    public class CoSoController : Controller
    {
        private readonly QlattpContext _context;

        public CoSoController(QlattpContext context)
        {
            _context = context;
        }

        // GET: CoSo
        public async Task<IActionResult> Index()
        {
            var coSoes = await _context.CoSos.ToListAsync();
            return View(coSoes);
        }

        // GET: CoSo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coSo = await _context.CoSos
                .FirstOrDefaultAsync(m => m.IdcoSo == id);
            if (coSo == null)
            {
                return NotFound();
            }

            return View(coSo);
        }

        // GET: CoSo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CoSo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdcoSo,IdchuCoSo,TenCoSo,DiaChi,IDPhuongXa,LoaiHinhKinhDoanh,SoGiayPhepKd,NgayCapGiayPhepKd,NgayCapCnattp,NgayHetHanCnattp,ChuCoSoId")] CoSo coSo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(coSo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coSo);
        }

        // GET: CoSo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coSo = await _context.CoSos.FindAsync(id);
            if (coSo == null)
            {
                return NotFound();
            }
            return View(coSo);
        }

        // POST: CoSo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdcoSo,IdchuCoSo,TenCoSo,DiaChi,IDPhuongXa,LoaiHinhKinhDoanh,SoGiayPhepKd,NgayCapGiayPhepKd,NgayCapCnattp,NgayHetHanCnattp,ChuCoSoId")] CoSo coSo)
        {
            if (id != coSo.IdcoSo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(coSo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoSoExists(coSo.IdcoSo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(coSo);
        }

        // GET: CoSo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coSo = await _context.CoSos
                .FirstOrDefaultAsync(m => m.IdcoSo == id);
            if (coSo == null)
            {
                return NotFound();
            }

            return View(coSo);
        }

        // POST: CoSo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coSo = await _context.CoSos.FindAsync(id);
            _context.CoSos.Remove(coSo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoSoExists(int id)
        {
            return _context.CoSos.Any(e => e.IdcoSo == id);
        }
    }
}

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}
@if (!string.IsNullOrEmpty(message))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>Hệ Thống Quản Lý An Toàn Vệ Sinh Thực Phẩm</title>

    <link rel="shortcut icon" type="image/x-icon" href="~/asset/assets/img/logo1.png">
    <link rel="stylesheet" href="~/asset/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/asset/assets/plugins/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/asset/assets/plugins/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/asset/assets/css/feathericon.min.css">
    <link rel="stylesheet" href="~/asset/assets/plugins/datatables/datatables.min.css">
    <link rel="stylesheet" href="~/asset/assets/plugins/morris/morris.css">
    <link rel="stylesheet" type="text/css" href="~/asset/assets/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="~/asset/assets/css/style.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    




</head>
<body>

    <div class="main-wrapper">

        <div class="header">

            <div class="header-left">
                <a href="index.html" class="logo">
                    <img src="~/asset/assets/img/logo1.png" width="50" height="70" alt="logo">
                    <span class="logoclass">Hệ Thống Quản Lý An Toàn Vệ Sinh Thực Phẩm</span>
                </a>
                <a href="index.html" class="logo logo-small">
                    <img src="~/asset/assets/img/logo1.png" alt="Logo" width="30" height="30">
                </a>
            </div>

            <a href="javascript:void(0);" id="toggle_btn">
                <i class="fe fe-text-align-left"></i>
            </a>

            <a class="mobile_btn" id="mobile_btn">
                <i class="fas fa-bars"></i>
            </a>


            <ul class="nav user-menu">
                @await Html.PartialAsync("_LoginPartial")
                @await Html.PartialAsync("_MenuManagePartial")
               @*  @await Html.PartialAsync("_MenuMemberManager") *@
            </ul>

        </div>


        <div class="sidebar" id="sidebar">
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                        <li>
                            <a href="/">
                                <i class="fas fa-tachometer-alt"></i> <span>Trang Chủ</span>
                            </a>
                            
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "HienThiTinTuc", new { area = "Blog" })">
                                <i class="fa fa-spinner fa-spin"></i> <span>Tin Tức</span>
                            </a>

                        </li>
                        <li class="submenu">
                            <a href="#"><i class="fas fa-suitcase"></i> <span> Đăng Ký Chứng Nhận  </span> <span class="menu-arrow"></span></a>
                            <ul class="submenu_class" style="display: none;">
                                <li><a href=@Url.Action("XemDanhSachHoSo", "DangkyATTP")> Danh Sách Hồ Sơ Đã Đăng Ký </a></li>
                                <li><a href=@Url.Action("DangKyGiayChungNhanMoi", "DangkyATTP")> Đăng Ký ATTP mới </a></li>
                                <li><a href=@Url.Action("DangKyLaiGiayChungNhan", "DangkyATTP")> Đăng Ký lại ATTP</a></li>
                            </ul>
                        </li>
                        <li class="submenu">
                            <a href="#"><i class="fas fa-user"></i> <span> Cơ Sở Kinh Doanh</span> <span class="menu-arrow"></span></a>
                            <ul class="submenu_class" style="display: none;">
                                <li><a href=@Url.Action("Index", "CoSo", new { area = "Blog" })> Quản lý Cơ Sở Kinh Doanh</a></li>
                                <li><a href=@Url.Action("Create", "CoSo", new { area = "Blog" })> Đăng Ký Cơ Sở Kinh Doanh </a></li>
                            </ul>
                        </li>
                        <li class="submenu">
                            <a href="#"><i class="fas fa-key"></i> <span> Báo Cáo Vi Phạm </span> <span class="menu-arrow"></span></a>
                            <ul class="submenu_class" style="display: none;">
                                <li><a href=@Url.Action("List", "BaoCaoViPham")> Danh sách báo Cáo </a></li>
                                <li><a href=@Url.Action("Index", "BaoCaoViPham")> Báo Cáo Vi Phạm </a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("SendContact", "Contact", new { area = "Contact" })">
                                <i class="fas fa-tachometer-alt"></i> <span>Liên Hệ</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Guide", "Home")">
                                <i class="fa fa-book"></i> <span>Hướng dẫn sử dụng</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="page-wrapper">

            @RenderBody()
           
           @*  <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderSection("scripts", required: false)
        </div>
  @*       <script src="~/asset/assets/js/jquery-3.5.1.min.js"></script> *@
        <script src="~/asset/assets/js/popper.min.js"></script>
        <script src="~/asset/assets/js/bootstrap.min.js"></script>
        <script src="~/asset/assets/js/moment.min.js"></script>
        <script src="~/asset/assets/js/select2.min.js"></script> 
        <script src="~/asset/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
        <script src="~/asset/assets/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/asset/assets/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="~/asset/assets/plugins/datatables/datatables.min.js"></script>
        <script src="~/asset/assets/plugins/raphael/raphael.min.js"></script>
        <script src="~/asset/assets/plugins/morris/morris.min.js"></script>
        <script src="~/asset/assets/js/chart.morris.js"></script>
        <script src="~/asset/assets/js/script.js"></script>
        <script>
            $(function () {
                $('#datetimepicker3').datetimepicker({
                    format: 'LT'
                });
            });
        </script>



        
</body>
</html>

Views/Shared/_MenuManagePartial.cshtml
@using Microsoft.AspNetCore.Authorization
@using WebAnToanVeSinhThucPhamDemo.Data
@inject IAuthorizationService authorizationService

@if (User.Identity.IsAuthenticated)
{
    var isAdmin = await authorizationService.AuthorizeAsync(this.User, "ViewManageMenu");
    var isEditor = this.User.IsInRole(RoleName.Editor);
    var isMember = await authorizationService.AuthorizeAsync(this.User, "MemberManagerMenu");

    <div class="dropdown">
        <a class="btn btn-outline-danger dropdown-toggle" href="#" id="managedropdownmenu" data-toggle="dropdown">
            Manage
        </a>
        <div class="dropdown-menu" aria-labelledby="managedropdownmenu">
            @if (isAdmin.Succeeded)
            {
                <a class="dropdown-item" asp-action="Index" asp-controller="DbManage" asp-area="Database">Database</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="Contact" asp-area="Contact">Quản lý liên hệ</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="Role" asp-area="Identity">Quản lý role (vai trò)</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Identity">Quản lý thành viên</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="CoSo" asp-area="Blog">Quản lý Cơ Sở</a>
            }

            @if (isAdmin.Succeeded || isEditor)
            {
                <a class="dropdown-item" asp-action="Index" asp-controller="DanhMuc" asp-area="Blog">Quản lý chuyên mục tin tức</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="TinTuc" asp-area="Blog">Quản lý tin tức</a>
                <a target="_blank" class="dropdown-item" asp-action="Index" asp-controller="FileManager" asp-area="Files">Quản lý files</a>
                <a class="dropdown-item" asp-action="Index" asp-controller="HoSoATTP" asp-area="HoSo">Quản lý hồ Sơ</a>
            }

            @if (isAdmin.Succeeded || isEditor || isMember.Succeeded)
            {
                <a class="dropdown-item" asp-area="Identity" asp-controller="Manage" asp-action="Index">Thông Tin Cá Nhân</a>
            }
        </div>
    </div>

    <style>
        .dropdown {
            margin-right: 50px; /* Tạo khoảng cách 20px với rìa phải */
        }
    </style>
}

Views/Shared/_MenuMemberManager.cshtml
@using Microsoft.AspNetCore.Authorization
@using WebAnToanVeSinhThucPhamDemo.Data
@inject IAuthorizationService authorizationService

@{
    var isMember = await authorizationService.AuthorizeAsync(this.User, "MemberManagerMenu");

}

@if (isMember.Succeeded)
{
    <div class="dropdown">
        <a class="btn btn-outline-danger dropdown-toggle" href="#" id="managedropdownmenu" data-toggle="dropdown">
            Manage
        </a>
        <div class="dropdown-menu" aria-labelledby="managedropdownmenu">
            @if (isMember.Succeeded)
            {


                <a class="dropdown-item" asp-area="Identity" asp-controller="Manage" asp-action="Index">
                    Thông Tin Cá Nhân
                </a>
                
            }
            
        </div>
    </div>
    <style>
        .dropdown {
            margin-right: 50px; /* Tạo khoảng cách 20px với rìa phải */
        }
    </style>
}

Views/Shared/_PagingXTL.cshtml
@* 
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model App.Models.PagingModel
@{
    int currentPage  = Model.currentpage;
    int countPages   = Model.countpages;
    var generateUrl  = Model.generateUrl;


    
    if (currentPage > countPages) 
      currentPage = countPages;

    if (countPages <= 1) return;
    

    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();    

        
    int delta      = 5;             // Số trang mở rộng về mỗi bên trang hiện tại     
    int remain     = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i  <= countPages) {
            pagesRanges.Add(currentPage + i); 
            remain --;
        }
               
        if (currentPage - i >= 1) {
            pagesRanges.Insert(0, currentPage - i);
            remain --;
        }
            
    }    
    // Xử lý thêm vào các trang cho đủ remain 
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0) {
        if (pagesRanges[0] == 1) {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages) {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1) {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }
      
    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage) {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }   
        else 
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else 
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>

Views/Shared/_StatusMessage.cshtml
@{
    var mgs = TempData["StatusMessage"] as string;
}

@if (!String.IsNullOrEmpty(mgs))
{
    var statusMessageClass = mgs.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @mgs
    </div>
}

Views/Shared/_Summernote.cshtml
@model WebAnToanVeSinhThucPhamDemo.Models.Summernote

@if (Model.LoadLibrary)
{
   <!-- Summernote -->
    <section>
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
    </section>

    <!-- elFinder -->
    <section>
        <link rel="stylesheet" href="~/lib/jqueryui/themes/base/theme.css" />
        <link rel="stylesheet" href="~/lib/jqueryui/themes/base/jquery-ui.css" />
        <link rel="stylesheet" href="~/lib/elfinder/css/elfinder.full.css" />
        <link rel="stylesheet" href="~/lib/elfinder/css/theme.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.min.css" />

        <script src="~/lib/elfinder/js/elfinder.min.js"></script>
    </section>
}
<script>

    (function (factory) {
        if (typeof define === 'function' && define.amd) {
            define(['jquery'], factory);
        }
        else if (typeof module === 'object' && module.exports) {
            module.exports = factory(require('jquery'));
        } else {
            factory(window.jQuery);
        }
    }(function ($) {
        $.extend($.summernote.plugins, {
            // Tạo plugin tên elfinder
            'elfinder': function (context) {
                var self = this;
                // ui has renders to build ui elements.
                var ui = $.summernote.ui;
                // Tạo nút bấm
                context.memo('button.elfinder', function () {
                    var button = ui.button({
                        contents: '<i class="note-icon-picture"/> elFinder',
                        tooltip: 'Quản lý file',
                        click: function () {
                            // Bấm vào nút bấm gọi hàm elfinderDialog
                            elfinderDialog(context);
                        }
                    });
                    // create jQuery object from button instance.
                    var $elfinder = button.render();
                    return $elfinder;
                });
                // This methods will be called when editor is destroyed by $('..').summernote('destroy');
                // You should remove elements on `initialize`.
                this.destroy = function () {
                    this.$panel.remove();
                    this.$panel = null;
                };
            }

        });
    }));

    function elfinderDialog(editor) {
        var fm = $('<div/>').dialogelfinder({

            baseUrl: "@Url.Content("~/lib/elfinder/")",
            url: "@Url.Action("Connector", "FileManager", new { area = "Files" })",

            lang: 'vi',
            width: 840,
            height: 450,
            destroyOnClose: true,
            getFileCallback: function (files, fm) {
                console.log(files);
                editor.invoke('editor.insertImage', files.url);
            },
            commandsOptions: {
                getfile: {
                    oncomplete: 'close',
                    folders: false
                }
            }
        }).dialogelfinder('instance');
    }

    $('@Model.IDEditor').summernote({
        height: @Model.height,
        toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video','elfinder']],
            ['view', ['fullscreen', 'codeview', 'help']]
        ]
    });

   
</script>