Controllers/DangkyATTPController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Framework;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Globalization;
using System.Security.Claims;
using System.Text.RegularExpressions;
using WebAnToanVeSinhThucPhamDemo.Data;
using WebAnToanVeSinhThucPhamDemo.Models;
using static System.Net.Mime.MediaTypeNames;

namespace WebAnToanVeSinhThucPhamDemo.Controllers
{
    [Authorize(Roles = RoleName.Editor + "," + RoleName.Member)]
    public class DangkyATTPController : Controller
    {
        private readonly QlattpContext _context;
        private readonly IWebHostEnvironment _webHost;
        private DataContext _dataContext;

        public DangkyATTPController(IWebHostEnvironment webHost, QlattpContext context)
        {
            _context = context;
            _webHost = webHost;
            _dataContext = new DataContext();
        }
        //Note
        public IActionResult DangKyGiayChungNhanMoi()
        {
            string tempPhuongXa = TempData["phuongXa"] == null ? "0" : TempData["phuongXa"].ToString();
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = "Chọn quận huyện", Value = "0" });
            foreach (var i in _context.QuanHuyen)
            {
                li.Add(new SelectListItem { Text = i.TenQuanHuyen, Value = i.IDQuanHuyen.ToString() });
            }
            ViewData["quanhuyen"] = li;

            List<SelectListItem> li2 = new List<SelectListItem>();
            li2.Add(new SelectListItem { Text = "Chọn phường xã", Value = "0" });
            foreach (var i in _context.PhuongXa)
            {
                if (tempPhuongXa == i.IDPhuongXa.ToString())
                {
                    li2.Add(new SelectListItem { Text = i.TenPhuongXa, Value = i.IDPhuongXa.ToString(), Selected = true });
                }
                else
                {
                    li2.Add(new SelectListItem { Text = i.TenPhuongXa, Value = i.IDPhuongXa.ToString(), Selected = false });
                }
            }
            ViewData["quanhuyen"] = li;
            ViewData["phuongxa"] = li2;
            return View("Index");
        }

        //Note
        [HttpPost] //Chạy cái action Insert của form ở view Index
        [ActionName("Insert")]
        public ActionResult DangKyGiayChungNhanMoi(IFormCollection form)
        {
            bool isValid = true;
            string tencoso = form["tencoso"];
            string phuongxa = form["phuongxa"];
            string diachi = form["diachi"];
            string loaihinhkinhdoanh = form["loaihinhkinhdoanh"];
            string sogiayphep = form["sogiayphep"];
            DateOnly ngaycap;
            isValid = DateOnly.TryParse(form["ngaycap"].ToString(), out ngaycap);

            string loaithucpham = form["loaithucpham"];

            //độ dài 10 -> 100, ko chứ kí tự đặc biệt !@#
            string checkSpecialCharacter = @"^[^!@#]{10,100}$";
            string checkString = @"^[^!@#0-9]{10,100}$";
            //kí tự đầu là 0, 9 kí tự sau là số
            string checkPhone = @"^[0][1-9]{9}$";
            string checkSoDoanhNghiep = @"^[0-9]{10}$";
            if (!new Regex(checkSpecialCharacter).IsMatch(tencoso))

            {
                isValid = false;
                TempData["errorTenCoSo"] = "Tên không hợp lệ.";
            }
            if (!new Regex(checkSpecialCharacter).IsMatch(diachi))
            {
                isValid = false;
                TempData["errorDiaChi"] = "Địa chỉ không hợp lệ.";
            }
            if(loaihinhkinhdoanh == "0")
            {
                isValid = false;
                TempData["errorLoaiHinhKinhDoanh"] = "Hãy chọn loại hình kinh doanh.";
            }
            if(phuongxa == "0")
            {
                isValid = false;
                TempData["errorPhuongXa"] = "Hãy chọn phường xã.";
            }
            if (!new Regex(checkSoDoanhNghiep).IsMatch(sogiayphep))
            {
                isValid = false;
                TempData["errorSoGiayPhep"] = "Số giấy phép kinh doanh không hợp lệ";
            }
            if(ngaycap.Year < 1900)
            {
                TempData["errorNgayCap"] = "Ngày cấp giấy phép kinh doanh không hợp lệ";
            }
            if(!new Regex(checkString).IsMatch(loaithucpham))
            {
                isValid = false;
                TempData["errorLoaiThucPham"] = "Loại thực phẩm không hợp lệ";
            }
            if (form.Files.Count < 4)
            {
                isValid = false;
                TempData["errorHinhAnh"] = "Số lượng hình ảnh không đủ";
            }
            if(isValid == false)
            {
                TempData["tenCoSo"] = tencoso;
                TempData["diaChi"] = diachi;
                TempData["phuongXa"] = phuongxa;
                TempData["loaiHinhKinhDoanh"] = loaihinhkinhdoanh;
                TempData["soGiayPhep"] = sogiayphep;
                string test = ngaycap.ToString("yyyy-MM-dd");
                TempData["ngayCap"] = test;
                TempData["loaiThucPham"] = loaithucpham;
                //TempData["hinhAnh"] = form.Files;
                return RedirectToActionPermanent("DangKyGiayChungNhanMoi");
            }
            else
            {
                try
                {
                    String imageNames = "";
                    String loaihinhkd;
                    foreach (var file in form.Files)
                    {
                        imageNames += file.FileName + ",";
                    }
                    if (loaihinhkinhdoanh == "1")
                        loaihinhkd = "Cơ sở sản xuất, kinh doanh thực phẩm";
                    else
                        loaihinhkd = "Cơ sở kinh doanh dịch vụ ăn uống";
                    // chay lenh insert
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    int maHoSo = _dataContext.insertGiayChungNhan_CoSo(userId, tencoso, Convert.ToInt16(phuongxa), diachi, loaihinhkd, sogiayphep, ngaycap, loaithucpham, imageNames);

                    //luu file
                    string uploadFolder = Path.Combine(_webHost.WebRootPath, "HoSoDangKyATTP", maHoSo.ToString());
                    if (!Directory.Exists(uploadFolder))
                    {
                        Directory.CreateDirectory(uploadFolder);
                    }
                    foreach (var file in form.Files)
                    {
                        SaveImage(file, uploadFolder);
                    }
                    TempData["AlertMessage"] = "Gửi thành công";
                    return RedirectToAction("DangKyGiayChungNhanMoi");
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex);
                    return Content("Đăng ký thất bại");
                }
            }  
        }

        //Function lưu hình ảnh
        public async void SaveImage(IFormFile file, string path)
        {
            string fileName = Path.GetFileName(file.FileName);
            string fileSavePath = Path.Combine(path, fileName);
            using (FileStream stream = new FileStream(fileSavePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
        }
        //Note
        public JsonResult GetPhuongXa(string id)
        {
            if (id == "0")
            {
                return Json(new SelectList(_context.PhuongXa, "IDPhuongXa", "TenPhuongXa"));
            }
            return Json(new SelectList(_context.PhuongXa.Where(x=> x.IDQuanHuyen.ToString()  == id), "IDPhuongXa", "TenPhuongXa"));
        }

        //Code đăng ký lại giấy chứng nhận
        [HttpGet]
        public IActionResult DangKyLaiGiayChungNhan()
        {
            //lấy danh sách cơ sở theo idChuCoSo
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var listCoSo = _context.CoSos.Where(a => a.ChuCoSoId == userId);
            ViewData["listCoSo"] = new SelectList(listCoSo, "IdcoSo", "TenCoSo");
            return View("Index1");
        }

        [HttpPost]
        public IActionResult DangKyLaiGiayChungNhan(string coso, string loaithucpham, List<IFormFile> hinhanh)
        {
            try
            {
                
                String imageNames = "";
                foreach (IFormFile file in hinhanh)
                {
                    imageNames += file.FileName + ",";
                }
                //insert HoSoDangKyGiayChungNhan
                int maHoSo = _dataContext.insertGiayChungNhan(Int32.Parse(coso), loaithucpham, imageNames);

                //luu file
                string uploadFolder = Path.Combine(_webHost.WebRootPath, "HoSoDangKyATTP", maHoSo.ToString());
                if (!Directory.Exists(uploadFolder))
                {
                    Directory.CreateDirectory(uploadFolder);
                }
                foreach (IFormFile file in hinhanh)
                {
                    SaveImage(file, uploadFolder);
                }
                return Content("Đăng ký thành công");

            }
            catch (Exception ex)
            {
                return Content("Đăng ký that bai");
            }
        }

        //Xem trang thai ho so
        [HttpGet]
        public IActionResult XemDanhSachHoSo()
        {
            var currentUserRole = User.FindFirstValue(ClaimTypes.Role);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            IQueryable<HoSoCapGiayChungNhan> hoSoQuery;

            if (currentUserRole == "Admin")
            {
                hoSoQuery = _context.HoSoCapGiayChungNhans
                    .Include(h => h.IdcoSoNavigation)
                        .ThenInclude(c => c.ChuCoSo);
            }
            else

Views/DangkyATTP/Index.cshtml
@{
	ViewBag.Title = "Index";
}
<link href="~/css/ImageClick.css" rel="stylesheet" />
<hr />

@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["AlertMessage"]
    </div>
}
<div class="content container-fluid">
    
    @*<div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Horizontal Form</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                    <li class="breadcrumb-item active">Horizontal Form</li>
                </ul>
            </div>
        </div>
    </div>*@

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Đăng ký giấy chứng nhận vệ sinh an toàn thực phẩm</h5>
                </div>
                <div class="card-body">
                    <form asp-action="Insert" method="post" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-xl-6">
                                <h5 class="card-title">Thông tin cơ sở</h5>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Tên cơ sở<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <input type="text" name="tencoso" class="form-control" value="@TempData["tenCoSo"]">
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorTenCoSo"]</div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Địa chỉ<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <input type="text" name="diachi" class="form-control" value="@TempData["diaChi"]">
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorDiaChi"]</div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Quận/Huyện</label>
                                    <div class="col-lg-8">
                                            <select class="form-select" id="quanhuyen" asp-items="@ViewBag.quanhuyen"></select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Phường/Xã<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <select id="phuongxa"  asp-items="@ViewBag.phuongxa" name="phuongxa">
                                        </select>
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorPhuongXa"]</div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Loại hình kinh doanh<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <select class="form-select" name="loaihinhkinhdoanh" >
                                            <option value="0">Select</option>
                                            <option value="1">Cơ sở sản xuất, kinh doanh thực phẩm</option>
                                            <option value="2">Cơ sở kinh doanh dịch vụ ăn uống</option>
                                        </select>
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorLoaiHinhKinhDoanh"]</div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Số giấy phép kinh doanh<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <input type="text" name="sogiayphep" class="form-control" value="@TempData["soGiayPhep"]">
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorSoGiayPhep"]</div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Ngày cấp giấy phép<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <input type="date" name="ngaycap" class="form-control" value="@TempData["ngayCap"]" >
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorNgayCap"]</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <h5 class="card-title">Thông tin giấy chứng nhận</h5>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Loại thực phẩm<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <input type="text" name="loaithucpham" class="form-control" value="@TempData["loaiThucPham"]">
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorLoaiThucPham"]</div>
                                    </div>            
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-4 col-form-label">Hình ảnh minh chứng<span class=".text-danger"> (*)</span></label>
                                    <div class="col-lg-8">
                                        <input id="files" type="file" name="hinhanh" class="form-control" accept="image/*" multiple>
                                        <div style="margin-top: .25rem;font-size: .875em;color: #dc3545;">@TempData["errorHinhAnh"]</div>
                                        <div id="preview"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-end">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                    <div id="myModal" class="modal">
                        <span class="close">&times;</span>
                        <img class="modal-content" id="img01">
                        <!-- <div id="caption"></div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
    	$("#quanhuyen").change(function () {
    		$.ajax({
    			type: 'POST',
    			url: '@Url.Action("GetPhuongXa")', // we are calling json method
    			dataType: 'json',
    			data: { id: $("#quanhuyen").val() },
    				success: function(phuongxas) {
                        $("#phuongxa").empty();
    					$.each(phuongxas, function (i, item ) {
                                $("#phuongxa").append('<option value="'
                            + item.value + '">'
                            + item.text + '</option>');

                    });
    				},
    			error: function (ex) {
    				alert('failed to retrieve states.' + ex);
    			}
    		})
    	})
    });
</script>

<script type="text/javascript">
    const removeoldImg = () => {
        var container = document.getElementById("preview");
        container.replaceChildren();
    }
    const preview = (file) => {
        removeoldImg();
        const fr = new FileReader();
        fr.onload = () => {
            const img = document.createElement("img");
            img.src = fr.result;  // String Base64
            img.alt = file.name;
            img.width = 100;
            img.height = 100;
            img.className = "myImages";
            img.onclick = function (evt) {
                modal.style.display = "block";
                modalImg.src = this.currentSrc;
            }
            document.querySelector('#preview').append(img);
            // to all images -- note I'm using a class!
            var images = document.getElementsByClassName('myImages');
        };
        fr.readAsDataURL(file);
    };
    // đổi #files sang id của input files
    document.querySelector("#files").addEventListener("change", (ev) => {
        if (!ev.target.files) return; // Do nothing.
        [...ev.target.files].forEach(preview);
    });
</script>
<script>
    // create references to the modal...
    var modal = document.getElementById('myModal');
    // to all images -- note I'm using a class!
    var images = document.getElementsByClassName('myImages');
    // the image in the modal
    var modalImg = document.getElementById("img01");
    var span = document.getElementsByClassName("close")[0];
    span.onclick = function () {
        modal.style.display = "none";
    }
</script>

Views/DangkyATTP/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Đăng ký giấy chứng nhận vệ sinh an toàn thực phẩm";
}
<div class="content container-fluid">

    @* <div class="page-header">
    <div class="row">
    <div class="col">
    <h3 class="page-title">Horizontal Form</h3>
    <ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
    <li class="breadcrumb-item active">Horizontal Form</li>
    </ul>
    </div>
    </div>
    </div> *@

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Đăng ký giấy chứng nhận vệ sinh an toàn thực phẩm</h5>
                </div>
                <div class="card-body">
                    <form asp-action="DangKyLaiGiayChungNhan" method="post" enctype="multipart/form-data">
                        <div class="row">
                            <div class="form-group col-12">
                                <label class="col-form-label">Cơ Sở</label>
                                <div class="">
                                    <select name="coso" asp-items="ViewBag.listCoSo"></select>
                                </div>
                            </div>
                            <div class="form-group col-12">
                                <label class=" col-form-label">Loại thực phẩm</label>
                                <div class="">
                                    <input type="text" name="loaithucpham" class="form-control">
                                </div>
                            </div>
                            <div class="form-group col-12">
                                <label class="col-form-label">Hình ảnh minh chứng</label>
                                <div class="">
                                    <input id="files" type="file" name="hinhanh" class="form-control" multiple>
                                    <div id="preview"></div>
                                </div>
                            </div>
                        </div>
                        <div class="text-end">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>


<script type="text/javascript">

    $(document).ready(function () {
        $("#quanhuyen").change(function () {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetPhuongXa")', // we are calling json method
                dataType: 'json',
                data: { id: $("#quanhuyen").val() },
                success: function (phuongxas) {
                    $("#phuongxa").empty();
                    $.each(phuongxas, function (i, item) {
                        $("#phuongxa").append('<option value="'
                            + item.value + '">'
                            + item.text + '</option>');

                    });
                },
                error: function (ex) {
                    alert('failed to retrieve states.' + ex);
                }
            })
        })
    });
</script>
<script type="text/javascript">
    const removeoldImg = () => {
        var container = document.getElementById("preview");
        container.replaceChildren();
    }
    const preview = (file) => {
        removeoldImg();
        const fr = new FileReader();
        fr.onload = () => {
            const img = document.createElement("img");
            img.src = fr.result;  // String Base64
            img.alt = file.name;
            img.width = 100;
            img.height = 100;
            img.className = "myImages";
            img.onclick = function (evt) {
                modal.style.display = "block";
                modalImg.src = this.currentSrc;
            }
            document.querySelector('#preview').append(img);
            // to all images -- note I'm using a class!
            var images = document.getElementsByClassName('myImages');
        };
        fr.readAsDataURL(file);
    };
    // đổi #files sang id của input files
    document.querySelector("#files").addEventListener("change", (ev) => {
        if (!ev.target.files) return; // Do nothing.
        [...ev.target.files].forEach(preview);
    });
</script>

Views/DangkyATTP/Index2.cshtml
@{
    ViewData["Title"] = "Danh sách hồ sơ";
}

@{

    Layout = "_Layout";
}

<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <div class="mt-5">
                    <h4 class="card-title float-left mt-2">Danh sách hồ sơ đã đăng ký</h4> <a href=@Url.Action("DangKyGiayChungNhanMoi", "DangkyATTP") class="btn btn-primary float-right veiwbutton">Đăng ký giấy chứng nhận ATTP</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="datatable table table-stripped">
                            <thead>
                                <tr>
                                    <th>Mã hồ sơ</th>
                                    <th>Tên cơ sở</th>
                                    <th>Tên chủ cơ sở</th>
                                    <th>Loại thực phẩm</th>
                                    <th>Hình ảnh</th>
                                    <th>Ngày đăng ký</th>
                                    <th>Trạng thái</th>
                                    <th class="text-right">Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var hoSo in ViewBag.ListHoSo)
                                {
                                    <tr>
                                        <td>@hoSo.maHoSo</td>
                                        <td>@hoSo.tencoso</td>
                                        <td>@hoSo.tenChuCoSo</td>
                                        <td>@hoSo.loaithucpham</td>
                                        <td>
                                            @foreach (var image in hoSo.hinhanh.Split(","))
                                            {
                                                @if (!image.Equals(""))
                                                {
                                                    <img src="@Url.Content("~/HoSoDangKyATTP/" + hoSo.maHoSo + "/" + image)" alt="Hình ảnh" width="100" height="100" />
                                                }
                                            }
                                        </td>
                                        <td>@hoSo.ngaydangky</td>
                                      
                                        <td>@(hoSo.trangthai == 1 ? "Đã duyệt" : "Chưa duyệt")</td>
                                        <td class="text-right">
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right"> <a class="dropdown-item" href="edit-asset.html"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a> <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a> </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="delete_asset" class="modal fade delete-modal" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <img src="assets/img/sent.png" alt="" width="50" height="46">
                    <h3 class="delete_class">Are you sure want to delete this Asset?</h3>
                    <div class="m-t-20">
                        <a href="#" class="btn btn-white" data-dismiss="modal">Close</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#datetimepicker3').datetimepicker({
            format: 'LT'
        });
    });
</script>

Views/DangkyATTP/Test.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="text-center">
    <h1 class="display-4">File upload</h1>
</div>
<div class="mb-3 mt-3">
    <form action="Test" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label class="form-label">Upload File</label>
            <input type="file" name="file" class="form-control" multiple/>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Upload</button>
        </div>
        <h1>@ViewBag.message</h1>
    </form>
</div>